### ISSUE TITLE
Ranking calculated in wrong order

### ISSUE THREAD

**Issue by OzQu** [bzar/kikkeri#7]
I created small test set of games: 
first game:       A vs B | 10 - 8     -> A should have 100 points
second game: A vs B | 10 - 4     -> A should have 100 more points, 200 in total
third game:     A vs C | 10 - 3     -> A should have 100 more points, 300 in total
fourth game:   A vs C | 10 - 3     -> A should have 100 more points, 400 in total
fifth game:      B vs C | 10 - 5     -> B should have 100 points

Ranking result were:
A -> 409
B -> 90
C -> 0

It seems like ranking calculating is done in reverse order.
fifth game:      B vs C | 10 - 5     -> B should have 100 points
fourth game:   A vs C | 10 - 3     -> A should have 100 points
third game:     A vs C | 10 - 3     -> A should have 100 more points, 200 in total
second game: A vs B | 10 - 4     -> A should have 109 more points, 309 in total and B should have 10 points less, 90 in total
first game:       A vs B | 10 - 8     -> A should have 100 more points, 409 total

**Comment by bzar** [comment]
Fixed by f001fdbfb3ddd66a60e66ffc6b512aa30e7b75b9
